### ISSUE TITLE
The test for float being loaded fails when listings is loaded before newfloat

### ISSUE THREAD

**Issue by eg9** [axelsommerfeldt/caption#5]
Analyzing the issue presented at https://tex.stackexchange.com/questions/416730/ I became aware of 
https://github.com/gpoore/pythontex/issues/61

The issue, as explained in my answer https://tex.stackexchange.com/a/416739/4427, is that `listings` uses `\@ifundefined{c@float@type}` in order to see whether `float` has been loaded, which leaves `\c@float@type` equivalent to `\relax`.

The `newfloat` package does the same check in the code for `\DeclareFloatingEnvironment`, but using `\ifdefined\c@float@type`. Unfortunately, if `listings` is loaded before `newfloat`, the test returns true instead of false.

This can, in principle, be solved by loading `newfloat` before `listings`, but classes may load `listings` without loading `newfloat` in advance. If a package is requested by the user (in the case under examination, `pythontex`) loads `newfloat`, an error happens.

In my opinion, `newfloat` should do its test with `\@ifundefined`.

**Comment by axelsommerfeldt** [comment]
Fixed with 309be570ec353b18dec4b882e99c287ed70e4a89

**Comment by axelsommerfeldt** [comment]
Backported to branch 3.3 with commit 0cd6e43480442cf316bcd01ed72a3a1f432c4116 and prepared for CTAN release with commit a5a0e2b65478ed4fb8d1239cd933264479a1d0b2
